import "./scripts/app.js"
import "./style.scss"
import "./scripts/dropdownmenu.js"
import "./scripts/setting.js"
import "./scripts/tester.js"
import "./scripts/shortparagraph.js"
import "./scripts/dummy1.js"
import "./scripts/dummy2.js"